/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class SampleTest {
    @Test public void testSample() {
        assertNotNull("This is a sample test", 1);
    }
}
